"""cron

Revision ID: de45134363a1
Revises: 7ae06613a752
Create Date: 2026-08-05 06:14:38.683881
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'de45134363a1'
down_revision: str | None = '7ae06613a752'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('on_missed', sa.String(length=16), nullable=False),
    sa.Column('last_fired_at', sa.BigInteger(), nullable=False),
    sa.Column('next_fire_at', sa.BigInteger(), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_cron_task_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cron_task'))
    )
    with op.batch_alter_table('cron_task', schema=None) as batch_op:
        batch_op.create_index('ix_cron_task_enabled', ['enabled'], unique=False)

    op.create_table('cron_run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('scheduled_at', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('finished_at', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['cron_task.id'], name=op.f('fk_cron_run_task_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cron_run'))
    )
    with op.batch_alter_table('cron_run', schema=None) as batch_op:
        batch_op.create_index('ix_cron_run_task_time', ['task_id', 'scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run', schema=None) as batch_op:
        batch_op.drop_index('ix_cron_run_task_time')

    op.drop_table('cron_run')
    with op.batch_alter_table('cron_task', schema=None) as batch_op:
        batch_op.drop_index('ix_cron_task_enabled')

    op.drop_table('cron_task')
    # ### end Alembic commands ###
