"""memory

Revision ID: 6a8e34f770cf
Revises: 7ae06613a752
Create Date: 2026-08-04 12:49:29.024667
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6a8e34f770cf'
down_revision: str | None = '7ae06613a752'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=64), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('hit', sa.Integer(), nullable=False),
    sa.Column('last_hit_at', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('origin_session_id', sa.String(length=32), nullable=False),
    sa.Column('archived_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory'))
    )
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.create_index('ix_memory_recall', ['archived_at', 'theme', 'hit'], unique=False)
        batch_op.create_index('ix_memory_updated', ['archived_at', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_index('ix_memory_updated')
        batch_op.drop_index('ix_memory_recall')

    op.drop_table('memory')
    # ### end Alembic commands ###
