"""add agent_ids to session

Revision ID: a334ba3b9193
Revises: 64f870b612ef
Create Date: 2026-08-14 20:26:04.951507
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a334ba3b9193'
down_revision: str | None = '64f870b612ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        # 添加新列（默认为空数组）
        batch_op.add_column(sa.Column('agent_ids', sa.Text(), nullable=False, server_default='[]'))

    # 数据迁移：将 agent_id 转换为 agent_ids JSON 数组
    # 如果 agent_id 非空，将其放入数组；否则保持空数组
    op.execute("""
        UPDATE session
        SET agent_ids = CASE
            WHEN agent_id = '' THEN '[]'
            ELSE '["' || agent_id || '"]'
        END
    """)

    with op.batch_alter_table('session', schema=None) as batch_op:
        # 删除旧列
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        # 添加旧列
        batch_op.add_column(sa.Column('agent_id', sa.VARCHAR(length=32), server_default=sa.text("('')"), nullable=False))

    # 数据迁移：从 agent_ids 提取第一个智能体
    # 如果数组为空或解析失败，设为空串
    op.execute("""
        UPDATE session
        SET agent_id = CASE
            WHEN agent_ids = '[]' THEN ''
            WHEN agent_ids LIKE '["__%"]' THEN SUBSTR(agent_ids, 3, LENGTH(agent_ids) - 4)
            ELSE ''
        END
    """)

    with op.batch_alter_table('session', schema=None) as batch_op:
        # 删除新列
        batch_op.drop_column('agent_ids')

    # ### end Alembic commands ###
