"""add_stream_enabled_and_extra_llm_params

Revision ID: 5af6b673978d
Revises: 59c26c359fb6
Create Date: 2026-08-17 14:37:49.759752
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5af6b673978d'
down_revision: str | None = '59c26c359fb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('agent_defs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_llm_params', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stream_enabled', sa.Integer(), nullable=False, server_default='1'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('stream_enabled')

    with op.batch_alter_table('agent_defs', schema=None) as batch_op:
        batch_op.drop_column('extra_llm_params')

    # ### end Alembic commands ###
