"""app_setting 表

Revision ID: 880f4dc6400e
Revises: e9452e1332a4
Create Date: 2026-08-13 19:01:57.879092

用户可调的运行时设置。key-value 而非每项一列 —— 设置会持续增加，
每加一个就要一次迁移。表里只存"用户改过的那些"，其余回落代码默认值，
所以"恢复默认"就是删行。
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '880f4dc6400e'
down_revision: str | None = 'e9452e1332a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_setting')
    # ### end Alembic commands ###
