"""add_agent_defs

Revision ID: 5fca3e61a094
Revises: f2a7c91d3b48
Create Date: 2026-08-08 22:42:27.923265
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5fca3e61a094'
down_revision: str | None = 'f2a7c91d3b48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'agent_defs',
        sa.Column('id', sa.String(32), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('avatar', sa.String(50), nullable=True),
        sa.Column('system_prompt', sa.Text(), nullable=False),
        sa.Column('model_id', sa.String(32), nullable=True),
        sa.Column('skill_names', sa.Text(), nullable=False),
        sa.Column('mcp_servers', sa.Text(), nullable=False),
        sa.Column('permission_read', sa.Integer(), nullable=False),
        sa.Column('permission_write', sa.Integer(), nullable=False),
        sa.Column('permission_shell', sa.Integer(), nullable=False),
        sa.Column('permission_network', sa.Integer(), nullable=False),
        sa.Column('permission_subagent', sa.Integer(), nullable=False),
        sa.Column('verification_enabled', sa.Integer(), nullable=False),
        sa.Column('strict_mode', sa.Integer(), nullable=False),
        sa.Column('hidden', sa.Integer(), nullable=False),
        sa.Column('max_turns', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_agent_defs_name', 'agent_defs', ['name'])
    op.create_index('ix_agent_defs_deleted', 'agent_defs', ['deleted_at'])

    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.String(length=32), nullable=False, server_default=''))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.String(length=32), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('agent_id')

    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
