"""initial

Revision ID: 541c243f54e9
Revises:
Create Date: 2026-08-03 07:39:26.937564
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '541c243f54e9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_whitelist',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('can_write', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('builtin', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_path_whitelist')),
    sa.UniqueConstraint('path', name=op.f('uq_path_whitelist_path'))
    )
    op.create_table('provider',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key_cipher', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('last_probe_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider')),
    sa.UniqueConstraint('name', name=op.f('uq_provider_name'))
    )
    op.create_table('workspace',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace')),
    sa.UniqueConstraint('root_path', name=op.f('uq_workspace_root_path'))
    )
    op.create_table('model',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('window_source', sa.String(length=16), nullable=False),
    sa.Column('supports_vision', sa.String(length=8), nullable=False),
    sa.Column('supports_tools', sa.String(length=8), nullable=False),
    sa.Column('vision_checked_at', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('fk_model_provider_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model'))
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index('ix_model_unique', ['provider_id', 'model_id'], unique=True)

    op.create_table('session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('pinned', sa.Integer(), nullable=False),
    sa.Column('approval_mode', sa.String(length=16), nullable=False),
    sa.Column('private_mode', sa.Integer(), nullable=False),
    sa.Column('amnesia_mode', sa.Integer(), nullable=False),
    sa.Column('vision_mode', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.BigInteger(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_session_workspace_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index('ix_session_list', [sa.text('pinned DESC'), sa.text('last_message_at DESC')], unique=False)

    op.create_table('message',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_display', sa.Text(), nullable=True),
    sa.Column('is_error', sa.Integer(), nullable=False),
    sa.Column('refs', sa.Text(), nullable=True),
    sa.Column('attachments', sa.Text(), nullable=True),
    sa.Column('artifact_kind', sa.String(length=16), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('span_id', sa.String(length=32), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_message_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('ix_message_artifact', ['session_id', 'agent_name'], unique=True, sqlite_where=sa.text("role = 'artifact'"))
        batch_op.create_index('ix_message_seq', ['session_id', 'seq'], unique=True)
        batch_op.create_index('ix_message_session', ['session_id', 'seq'], unique=False)

    op.create_table('model_binding',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('model_pk', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_pk'], ['model.id'], name=op.f('fk_model_binding_model_pk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_binding'))
    )
    with op.batch_alter_table('model_binding', schema=None) as batch_op:
        batch_op.create_index('ix_binding_unique', ['agent_name', 'purpose'], unique=True)

    op.create_table('todo',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_todo_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo'))
    )
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_index('ix_todo_session', ['session_id', 'archived_at', 'order_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index('ix_todo_session')

    op.drop_table('todo')
    with op.batch_alter_table('model_binding', schema=None) as batch_op:
        batch_op.drop_index('ix_binding_unique')

    op.drop_table('model_binding')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('ix_message_session')
        batch_op.drop_index('ix_message_seq')
        batch_op.drop_index('ix_message_artifact', sqlite_where=sa.text("role = 'artifact'"))

    op.drop_table('message')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_list')

    op.drop_table('session')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index('ix_model_unique')

    op.drop_table('model')
    op.drop_table('workspace')
    op.drop_table('provider')
    op.drop_table('path_whitelist')
    # ### end Alembic commands ###
