"""memory_extraction_watermark

Revision ID: 64f870b612ef
Revises: 880f4dc6400e
Create Date: 2026-08-14 15:46:44.187925
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '64f870b612ef'
down_revision: str | None = '880f4dc6400e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_extraction',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('extraction_count', sa.Integer(), nullable=False),
    sa.Column('last_report', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], name=op.f('fk_memory_extraction_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'agent_id', name=op.f('pk_memory_extraction'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_extraction')
    # ### end Alembic commands ###
