"""trace_span_run

Revision ID: 7ae06613a752
Revises: 541c243f54e9
Create Date: 2026-08-04 09:31:30.719590
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7ae06613a752'
down_revision: str | None = '541c243f54e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('parent_run_id', sa.String(length=32), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stop_reason', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('ended_at', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('rollup_total_tokens', sa.Integer(), nullable=False),
    sa.Column('rollup_cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run'))
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index('ix_run_created', ['created_at'], unique=False)
        batch_op.create_index('ix_run_parent', ['parent_run_id'], unique=False)
        batch_op.create_index('ix_run_session_started', ['session_id', 'started_at'], unique=False)

    op.create_table('span',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('parent_span_id', sa.String(length=32), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('ended_at', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_preview', sa.Text(), nullable=False),
    sa.Column('input_truncated', sa.Boolean(), nullable=False),
    sa.Column('input_bytes', sa.Integer(), nullable=False),
    sa.Column('output_preview', sa.Text(), nullable=False),
    sa.Column('output_truncated', sa.Boolean(), nullable=False),
    sa.Column('output_bytes', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('price_in_per_1m', sa.Float(), nullable=True),
    sa.Column('price_out_per_1m', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_span'))
    )
    with op.batch_alter_table('span', schema=None) as batch_op:
        batch_op.create_index('ix_span_created', ['created_at'], unique=False)
        batch_op.create_index('ix_span_parent', ['parent_span_id'], unique=False)
        batch_op.create_index('ix_span_run_started', ['run_id', 'started_at'], unique=False)
        batch_op.create_index('ix_span_session', ['session_id'], unique=False)

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_in_per_1m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_out_per_1m', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('price_out_per_1m')
        batch_op.drop_column('price_in_per_1m')

    with op.batch_alter_table('span', schema=None) as batch_op:
        batch_op.drop_index('ix_span_session')
        batch_op.drop_index('ix_span_run_started')
        batch_op.drop_index('ix_span_parent')
        batch_op.drop_index('ix_span_created')

    op.drop_table('span')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index('ix_run_session_started')
        batch_op.drop_index('ix_run_parent')
        batch_op.drop_index('ix_run_created')

    op.drop_table('run')
    # ### end Alembic commands ###
