"""add_level_to_memory_index

Revision ID: 2caff439cec9
Revises: a334ba3b9193
Create Date: 2026-08-15 17:06:13.404395
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2caff439cec9'
down_revision: str | None = 'a334ba3b9193'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='2'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_index', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
